name: 📚 Docs Report
labels: '📖 documentation'
description: Report an issue with the documentation

body:
  - type: textarea
    id: description
    attributes:
      label: Describe in more details
      description: More details about the documentation issue
      placeholder: Docs description