name: Compile and check

on:
  push:
    branches:
      - main
      - dev

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./scripts/build.sh