name: Compile and check

on:
  push:
    branches:
      - main
      - dev

env:
  TARGETS: "r-type_client r-type_server"

jobs:
  compile-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake build-essential libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile & Install dependencies
        run: | 
          git submodule update --init --recursive
          cmake -B build -S .

      - name: Build
        run: cmake --build build --target $TARGETS

  compile-windows:
    runs-on: windows-latest
    steps:
      - name: Install dependencies
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' 
          choco install mingw
          Import-Module "$env:ChocolateyInstall/helpers/chocolateyProfile.psm1"
          refreshenv

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: | 
          git submodule update --init --recursive
          cmake -G "MinGW Makefiles" -B build -S .

      - name: Build
        run: cmake --build build --target ${{ env.TARGETS }}
