name: Release Pull Request Naming Check

# Runs when a PR is opened, reopened, or synchronized.
# Checks if the PR title is a valid version number (e.g 1.3.0).

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
    branches:
      - main

jobs:
  release_pr_opened:
    if: github.event.pull_request.head.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check PR title
        run: bash scripts/check-version-name.sh ${{ github.event.pull_request.title }}
